
// Demo keys, generated by a free online service
// No sane person would ever use these

window.pgp_keys = {

    address: "mailbuild@kreata.ee",

    passphrase: "mailbuild",

    public_key: "-----BEGIN PGP PUBLIC KEY BLOCK-----\n"+
                "Version: BCPG C# v1.6.1.0\n"+
                "\n"+
                "mQENBFLtKGwBCACngAMLDAm2FDgb/KUrgtF/rQcPJZ8glv0ngYEdDqY/WohPo5Nn\n"+
                "VETSeW9gSEpzQ6v1dMcILJnE2ux8wCbI8mTLp/Dljy8BxTAQnasP6KS1KftIMuOo\n"+
                "v7cDOXd1zebY7h8841n2d10Mpf/WBMI3Bk6tNpwx6OSdBwZHIbbsN06QOr6S6vo3\n"+
                "mTti9lQymXr9Zp6ejfkCEludbwxaFZdQDi5kf2eyj4a4zJ/SNgzpVOhXIlKx4jpl\n"+
                "uwjwfsp39cIJD4sTjCVMs6ynkhvz9R5/d3/hNGaTxCmzew5yF09mwEJvv/E1UNi7\n"+
                "GXDjdy2URmccC2r12rZ78ZH1gi201tETapcxABEBAAG0E21haWxidWlsZEBrcmVh\n"+
                "dGEuZWWJARwEEAECAAYFAlLtKGwACgkQh59jkm1rURrXaQf/WWkfynzFIs+4PpEG\n"+
                "jiG5vNKtwrF++JKhpzIofbIVfKTsgsn6GAKCva7hSzhg5LuD/uQKTjWiUR2BV1G8\n"+
                "Fa59KzCUfC4k+81gG4cu/x1nE1dGYCvH2+7WUlwj+WWPqHSA6LZhay87U8Icno+U\n"+
                "VGmauZRyUkSYQss/qzLrSPnf5gI8N75Mveqd6pNG1MhZK/ZSJbTbXu4uEbvtmYrF\n"+
                "I10q8nMRngfUyzkoIOzxTf7hv/Smk+LlKTnOlyJb0Q31HGTGTxjM15ZbUCXGxkcQ\n"+
                "8dlYBFl6AtvENLZwG//4Uy8mLHRmbnvlUir/OjL2BssnjP3Ub9MedosG9O3b2zXH\n"+
                "Zg3Vrg==\n"+
                "=qDiJ\n"+
                "-----END PGP PUBLIC KEY BLOCK-----",

    private_key:"-----BEGIN PGP PRIVATE KEY BLOCK-----\n"+
                 "Version: BCPG C# v1.6.1.0\n"+
                 "\n"+
                 "lQOsBFLtKGwBCACngAMLDAm2FDgb/KUrgtF/rQcPJZ8glv0ngYEdDqY/WohPo5Nn\n"+
                 "VETSeW9gSEpzQ6v1dMcILJnE2ux8wCbI8mTLp/Dljy8BxTAQnasP6KS1KftIMuOo\n"+
                 "v7cDOXd1zebY7h8841n2d10Mpf/WBMI3Bk6tNpwx6OSdBwZHIbbsN06QOr6S6vo3\n"+
                 "mTti9lQymXr9Zp6ejfkCEludbwxaFZdQDi5kf2eyj4a4zJ/SNgzpVOhXIlKx4jpl\n"+
                 "uwjwfsp39cIJD4sTjCVMs6ynkhvz9R5/d3/hNGaTxCmzew5yF09mwEJvv/E1UNi7\n"+
                 "GXDjdy2URmccC2r12rZ78ZH1gi201tETapcxABEBAAH/AwMCLPX5IE8k21BgstoU\n"+
                 "4/JKlH/Lu+n5WjPBODKoqfK2xRLiUHENqC2ud4p7r+FicXJ6TCGqJrWSsHZUD/ps\n"+
                 "GEAhb9NsYb4YPliQ8PeXAH+kw08e7WF4qRhvG/vRUXdPR74G1zfxmepIOZ6KYpIx\n"+
                 "7uB6DS1YhFGXbNN9v5P8o4ff7oPkXZ/lZGt7FUcB3ySFQWZ5F72nfZPrHYXCJtk5\n"+
                 "3L3aa9k8dhw7EYZYMJJUt67lj+DU6fSU7JTCXx6sk5SuhbjHB4aZIwyTscXzaJNm\n"+
                 "Bkzk4xkITkEN617nVF7SrBC93ZFMcc8SwGLAZ3RxMJdr3liXUH5vge8be0Kk//7u\n"+
                 "j5CARAq7ZBRysh/mvudIrliEDFK5+Hp6NXZQDauJDASIdiau6+3IwEsWs64g93KI\n"+
                 "bkwmT7F+9AO38v/yyCrw9wf3vBAOUrXGU42JF/BLQ1XiwDfV2C1nkcr9hdP6eCgw\n"+
                 "oA8DrsY1G7qxkTUIZ5Kb1jB0AT9c6ftrZ3/lseoH1mqnBVGpS9aCC3mPArd6oF8B\n"+
                 "qRNTltv7P02uFec9yy51lIQblyRDznGLJ7fk2s8BLJqA0u7s3SCveU7JYf6VJJPF\n"+
                 "27kNGscfwzjfChCQESjrubxyHBMP1Ai4DWaBOTPe6MY90nb8OEgaB6vKzGfwNX71\n"+
                 "k2cI1drqI+xTDuwFWhEgFLG9iyKV+r4I7MAroionu/YzaDLGRJ+So2kuuFYfVs0o\n"+
                 "CTy0stoLr8RCoouTHoMVohgidVhsU2icvkNqPUfxGrLo85SWixCRcJuHYKP1GuD5\n"+
                 "g/wGfv3E3NyiN8byznefqmsPBmcDtJF5BML/zIg9HLEeiu2jlDXC99e8oFy+xdPQ\n"+
                 "j3rBw++Gu0+gRJOZTZDkWbMNBRJSvp8HbCzP5JbmiLQTbWFpbGJ1aWxkQGtyZWF0\n"+
                 "YS5lZYkBHAQQAQIABgUCUu0obAAKCRCHn2OSbWtRGtdpB/9ZaR/KfMUiz7g+kQaO\n"+
                 "Ibm80q3CsX74kqGnMih9shV8pOyCyfoYAoK9ruFLOGDku4P+5ApONaJRHYFXUbwV\n"+
                 "rn0rMJR8LiT7zWAbhy7/HWcTV0ZgK8fb7tZSXCP5ZY+odIDotmFrLztTwhyej5RU\n"+
                 "aZq5lHJSRJhCyz+rMutI+d/mAjw3vky96p3qk0bUyFkr9lIltNte7i4Ru+2ZisUj\n"+
                 "XSrycxGeB9TLOSgg7PFN/uG/9KaT4uUpOc6XIlvRDfUcZMZPGMzXlltQJcbGRxDx\n"+
                 "2VgEWXoC28Q0tnAb//hTLyYsdGZue+VSKv86MvYGyyeM/dRv0x52iwb07dvbNcdm\n"+
                 "DdWu\n"+
                 "=pgVS\n"+
                 "-----END PGP PRIVATE KEY BLOCK-----"
};
